### ISSUE TITLE
Memory corruption reported when killing Franklin with ctrl-C

### ISSUE THREAD

**Issue by wijnen** [mtu-most/franklin#59]
Sometimes when killing Franklin with ctrl-C, after the traceback a memory corruption warning is emitted. This suggests that something is not handled properly by the cdriver module.

Example traceback:
^CTraceback (most recent call last):
  File "./server.py", line 974, in <module>
Traceback (most recent call last):
  File "/home/debian/franklin/server/driver.py", line 2787, in <module>
    websocketd.fgloop()
  File "/usr/lib/python3/dist-packages/websocketd.py", line 1340, in fgloop
    return network.fgloop(*a, **ka)
  File "/usr/lib/python3/dist-packages/network.py", line 623, in fgloop
    iteration(len(_idle) == 0)
    found = select.select(fds, [], fds, None)
  File "/usr/lib/python3/dist-packages/network.py", line 575, in iteration
KeyboardInterrupt
    ret = select.select(_fds[0], _fds[1], _fds[0] + _fds[1])
KeyboardInterrupt
*** Error in `/usr/bin/python3': munmap_chunk(): invalid pointer: 0x007a4550 ***

**Comment by wijnen** [comment]
This has been fixes when I fixed all the reference counting mistakes I made in the Python module.
